[jwt]
secret = "fAT34EQqI6hhYlghZ+ZWM7bCLHcZZpJyb3x8DcxoJPM="

[http]
name = "web_app"
mode = "development"
port = "8080"

#业务相关参数
[app]
#定时器运行间隔(seconds 默认：1800)
auction_run_interval = 5#应当禁止发布小于这个时间的拍卖
#在当前时间范围内的时间区域(seconds 默认：3600 极限3600s)
#todo 启动的时候清理process 就可以避免系统不在线期间的超时拍卖订单
auction_time_start_offset = 17280000
auction_time_end_offset = 3600

[log]
level = "debug"
filename_debug = "/var/log/auction-website/debug.log"
filename_info = "/var/log/auction-website/info.log"
filename_error = "/var/log/auction-website/error.log"
max_size = 200
max_age = 30
max_backups = 7

[mysql]
host = "mysql"
dbname = "dev_auction"
user = "root"
password = "123456"

[mongodb]
host = "mongodb"
dbname = "dev_auction"
username = "root"
password = "123456"

[redis]
host = "redis"
db = 0
username = "default"
password = "ryD$S*#8MX$x@azD#XEzfsxNSNNQG70_"

[nsqd]
host = "nsqd"
# 供消费者、nsqlookupd 连接,用于消息消费和内部通信
tcp_port = 4150
# 提供 HTTP API,供生产者等客户端使用,方便管理和消息发布
http_port = 4151

[nsqlookupd]
host = "nsqlookupd"
# TCP端口,用于nsqd连接
tcp_port = 4160
# HTTP API端口
http_port = 4161

# topic 和 channel
[nsq.auction]
topic_name = "auction"
#描述当前在发生的事件 比如拍卖上架完成->发布消息

#[nsq]
#[nsq.auction]
#topic = "auction"
#ch = {caf = "create_auction_finished"}

[qiniu]
access_key = "zmdAcy1cDFyA7zYKGZ67e0o0NNlwp7hx74KRnjlr"
secret_key = "4l2c07UDBa-KNdNbV82GSgWKzbKVAkZl-O1rBUa8"
[qiniu.bucket]
auciton = "dev-auciton"
tmp_auciton = "tmp-dev-auciton"


[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "前端"

[servers.beta]
ip = "10.0.0.2"
role = "后端"